import Head from 'next/head'
import { signOut } from "next-auth/react";
import Header from "../components/Header"
export default function Home() {
  return (
    <>
      <Head>
        <title>WorkConnect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
    </>
  )
}
